In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import numpy as np
import pandas as pd
from pathlib import Path
from collections import Counter
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import confusion_matrix
from imblearn.metrics import classification_report_imbalanced
from sklearn.model_selection import train_test_split
from imblearn.over_sampling import RandomOverSampler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from imblearn.under_sampling import ClusterCentroids
from imblearn.over_sampling import SMOTE
from imblearn.combine import SMOTEENN

In [3]:
# Load the data
file_path = Path('C:/Users/saif_/Downloads/lending_data.csv')
df = pd.read_csv(file_path)

df.head()

loan_amnt  int_rate  installment  annual_inc loan_status    dti  \
0    10500.0    0.1719       375.35     66000.0    low_risk  27.24   
1    25000.0    0.2000       929.09    105000.0    low_risk  20.23   
2    20000.0    0.2000       529.88     56000.0    low_risk  24.26   
3    10000.0    0.1640       353.55     92000.0    low_risk  31.44   
4    22000.0    0.1474       520.39     52000.0    low_risk  18.76   

   delinq_2yrs  inq_last_6mths  open_acc  pub_rec  ...  \
0          0.0             0.0       8.0      0.0  ...   
1          0.0             0.0      17.0      1.0  ...   
2          0.0             0.0       8.0      0.0  ...   
3          0.0             1.0      10.0      1.0  ...   
4          0.0             1.0      14.0      0.0  ...   

   home_ownership_MORTGAGE  home_ownership_OWN  home_ownership_RENT  \
0                        0                   0                    1   
1                        1                   0                    0   
2                        1                   0                    0   
3                        0                   0                    1   
4                        1                   0                    0   

   verification_status_Source Verified  verification_status_Verified  \
0                                    1                             0   
1                                    0                             1   
2                                    0                             1   
3                                    0                             1   
4                                    0                             0   

   issue_d_Jan-2019  issue_d_Mar-2019  initial_list_status_w  \
0                 0                 1                      1   
1                 0                 1                      1   
2                 0                 1                      1   
3                 0                 1                      1   
4                 0                 1                      1   

   next_pymnt_d_May-2019  application_type_Joint App  
0                      1                           0  
1                      1                           0  
2                      1                           0  
3                      1                           0  
4                      1                           0  

[5 rows x 87 columns]

In [4]:
# Create our target
y = df["loan_status"]
# Create our features
X = df.drop(columns="loan_status")

In [5]:
X.describe()

loan_amnt      int_rate   installment    annual_inc           dti  \
count  68817.000000  68817.000000  68817.000000  6.881700e+04  68817.000000   
mean   16677.594562      0.127718    480.652863  8.821371e+04     21.778153   
std    10277.348590      0.048130    288.062432  1.155800e+05     20.199244   
min     1000.000000      0.060000     30.890000  4.000000e+01      0.000000   
25%     9000.000000      0.088100    265.730000  5.000000e+04     13.890000   
50%    15000.000000      0.118000    404.560000  7.300000e+04     19.760000   
75%    24000.000000      0.155700    648.100000  1.040000e+05     26.660000   
max    40000.000000      0.308400   1676.230000  8.797500e+06    999.000000   

        delinq_2yrs  inq_last_6mths      open_acc       pub_rec  \
count  68817.000000    68817.000000  68817.000000  68817.000000   
mean       0.217766        0.497697     12.587340      0.126030   
std        0.718367        0.758122      6.022869      0.336797   
min        0.000000        0.000000      2.000000      0.000000   
25%        0.000000        0.000000      8.000000      0.000000   
50%        0.000000        0.000000     11.000000      0.000000   
75%        0.000000        1.000000     16.000000      0.000000   
max       18.000000        5.000000     72.000000      4.000000   

           revol_bal  ...  home_ownership_MORTGAGE  home_ownership_OWN  \
count   68817.000000  ...             68817.000000        68817.000000   
mean    17604.142828  ...                 0.526309            0.106747   
std     21835.880400  ...                 0.499311            0.308793   
min         0.000000  ...                 0.000000            0.000000   
25%      6293.000000  ...                 0.000000            0.000000   
50%     12068.000000  ...                 1.000000            0.000000   
75%     21735.000000  ...                 1.000000            0.000000   
max    587191.000000  ...                 1.000000            1.000000   

       home_ownership_RENT  verification_status_Source Verified  \
count         68817.000000                         68817.000000   
mean              0.357659                             0.373992   
std               0.479314                             0.483865   
min               0.000000                             0.000000   
25%               0.000000                             0.000000   
50%               0.000000                             0.000000   
75%               1.000000                             1.000000   
max               1.000000                             1.000000   

       verification_status_Verified  issue_d_Jan-2019  issue_d_Mar-2019  \
count                  68817.000000      68817.000000      68817.000000   
mean                       0.148001          0.451066          0.177238   
std                        0.355104          0.497603          0.381873   
min                        0.000000          0.000000          0.000000   
25%                        0.000000          0.000000          0.000000   
50%                        0.000000          0.000000          0.000000   
75%                        0.000000          1.000000          0.000000   
max                        1.000000          1.000000          1.000000   

       initial_list_status_w  next_pymnt_d_May-2019  \
count           68817.000000           68817.000000   
mean                0.876121               0.616839   
std                 0.329446               0.486161   
min                 0.000000               0.000000   
25%                 1.000000               0.000000   
50%                 1.000000               1.000000   
75%                 1.000000               1.000000   
max                 1.000000               1.000000   

       application_type_Joint App  
count                68817.000000  
mean                     0.139660  
std                      0.346637  
min                      0.000000  
25%                      0.000000  
50%                      0.000000  

In [6]:
# Check the balance of our target values
df['loan_status'].value_counts()

low_risk     68470
high_risk      347
Name: loan_status, dtype: int64

In [7]:
# Create X_train, X_test, y_train, y_test
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, 
                                                    y, 
                                                    random_state=1, 
                                                    stratify=y)
X_train.shape

(51612, 86)

In [8]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(solver='lbfgs', random_state=1)
model.fit(X_train, y_train)

LogisticRegression(random_state=1)

In [9]:
# Calculated the balanced accuracy score
from sklearn.metrics import balanced_accuracy_score
y_pred = model.predict(X_test)
balanced_accuracy_score(y_test, y_pred)

0.5

In [10]:
# Display the confusion matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[    0,    87],
       [    0, 17118]], dtype=int64)

In [11]:
# Print the imbalanced classification report
from imblearn.metrics import classification_report_imbalanced
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

  high_risk       0.00      0.00      1.00      0.00      0.00      0.00        87
   low_risk       0.99      1.00      0.00      1.00      0.00      0.00     17118

avg / total       0.99      0.99      0.01      0.99      0.00      0.00     17205



In [12]:
# Resample the training data with the RandomOversampler
from imblearn.over_sampling import RandomOverSampler

ros = RandomOverSampler(random_state=1)
X_resampled, y_resampled = ros.fit_resample(X_train, y_train)
Counter(y_resampled)

Counter({'low_risk': 51352, 'high_risk': 51352})

In [13]:
# Train the Logistic Regression model using the resampled data
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(solver='lbfgs', random_state=1)
model.fit(X_resampled, y_resampled)

LogisticRegression(random_state=1)

In [14]:
# Calculated the balanced accuracy score
from sklearn.metrics import balanced_accuracy_score

balanced_accuracy_score(y_test, y_pred)

0.5

In [15]:
# Display the confusion matrix
from sklearn.metrics import confusion_matrix

y_pred = model.predict(X_test)
confusion_matrix(y_test, y_pred)

array([[   54,    33],
       [ 5797, 11321]], dtype=int64)

In [16]:
# Print the imbalanced classification report
from imblearn.metrics import classification_report_imbalanced

print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

  high_risk       0.01      0.62      0.66      0.02      0.64      0.41        87
   low_risk       1.00      0.66      0.62      0.80      0.64      0.41     17118

avg / total       0.99      0.66      0.62      0.79      0.64      0.41     17205



In [17]:
# Resample the training data with SMOTE
from imblearn.over_sampling import SMOTE

X_resampled, y_resampled = SMOTE(random_state=1, sampling_strategy=1.0).fit_resample(
    X_train, y_train
)
from collections import Counter

Counter(y_resampled)

Counter({'low_risk': 51352, 'high_risk': 51352})

In [18]:
# Train the Logistic Regression model using the resampled data
model = LogisticRegression(solver='lbfgs', random_state=1)
model.fit(X_resampled, y_resampled)

LogisticRegression(random_state=1)

In [19]:
# Calculated the balanced accuracy score
y_pred = model.predict(X_test)
balanced_accuracy_score(y_test, y_pred)

0.6225227729633256

In [20]:
# Display the confusion matrix
confusion_matrix(y_test, y_pred)

array([[   51,    36],
       [ 5840, 11278]], dtype=int64)

In [21]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

  high_risk       0.01      0.59      0.66      0.02      0.62      0.38        87
   low_risk       1.00      0.66      0.59      0.79      0.62      0.39     17118

avg / total       0.99      0.66      0.59      0.79      0.62      0.39     17205



In [ ]:
# Resample the data using the ClusterCentroids resampler
from imblearn.under_sampling import ClusterCentroids

cc = ClusterCentroids(random_state=1)
X_resampled, y_resampled = cc.fit_resample(X_train, y_train)

from collections import Counter

Counter(y_resampled)